# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Derick Nyende/Documents/GitHub/EEE4120F/YODA Project/YODA Project/YODA Project.srcs/sources_1/ip/bram_encoded_message/bram_encoded_message.xci
# IP: The module: 'bram_encoded_message' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Derick Nyende/Documents/GitHub/EEE4120F/YODA Project/YODA Project/YODA Project.srcs/sources_1/ip/bram_encoded_message/bram_encoded_message_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_encoded_message'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Derick Nyende/Documents/GitHub/EEE4120F/YODA Project/YODA Project/YODA Project.srcs/sources_1/ip/bram_encoded_message/bram_encoded_message.xci
# IP: The module: 'bram_encoded_message' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Derick Nyende/Documents/GitHub/EEE4120F/YODA Project/YODA Project/YODA Project.srcs/sources_1/ip/bram_encoded_message/bram_encoded_message_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_encoded_message'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
